name: Daily Platform Build

on: [pull_request, workflow_dispatch]

jobs:
  build_memgraph:
    name: "Build memgraph Debian 11"
    runs-on: [self-hosted, DockerMgBuild, X64]
    timeout-minutes: 60
    steps:
      - name: "Set up repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required because of release/get_version.py
          token: ${{ secrets.PAT }}
      - name: "Build package"
        run: |
          git clone -b master https://github.com/memgraph/memgraph.git
          cd memgraph
          ./release/package/run.sh package debian-11 Release
      - name: "Upload package"
        uses: actions/upload-artifact@v3
        with:
          name: memgraph-debian-11
          path: memgraph/build/output/debian-11/memgraph*.deb
  
  build_memgraph_arm:
    name: "Build memgraph Debian 11 ARM"
    runs-on: [self-hosted, DockerMgBuild, ARM64, strange]
    timeout-minutes: 120
    steps:
      - name: "Set up repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required because of release/get_version.py
          token: ${{ secrets.PAT }}
      - name: "Build package"
        run: |
          git clone -b master https://github.com/memgraph/memgraph.git
          cd memgraph
          ./release/package/run.sh package debian-11-arm Release
      - name: "Upload package"
        uses: actions/upload-artifact@v3
        with:
          name: memgraph-debian-aarch64
          path: memgraph/build/output/debian-11-arm/memgraph*.deb
