name: Daily Platform Build

on: [pull_request, workflow_dispatch]

jobs:
  platform_build:
    name: "Platform build"
    runs-on: [self-hosted, Linux, X64, Diff]
    env:
      THREADS: 24

    steps:
      - name: Set up repository
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. `0` indicates all history for all
          # branches and tags. (default: 1)
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Build community binaries
        run: |
          git clone -b master https://github.com/memgraph/memgraph.git

          cd memgraph

          # Activate toolchain.
          source /opt/toolchain-v4/activate

          # Initialize dependencies.
          ./init

          # Build community binaries.
          cd build
          cmake -DCMAKE_BUILD_TYPE=release -DMG_ENTERPRISE=OFF ..
          make -j$THREADS

          cd output
          cpack -G DEB --config "../CPackConfig.cmake"

      # - name: Build deb image
      #   run: |
      #     cd scripts/
      #     ./build_deb.sh master daily-deb

      # - name: Build MAGE image
      #   run: |
      #     ./build_mage_img.sh main daily-mage daily-deb

      # - name: Build platform image
      #   run: |
      #     ./build_platform_img.sh master daily-build ${{ secrets.PAT }}

