name: Daily Platform Build

on: [pull_request, workflow_dispatch]

jobs:
  platform_build:
    name: "Platform build"
    runs-on: [self-hosted, Linux, X64, Diff]
    env:
      THREADS: 24
      MEMGRAPH_ENTERPRISE_LICENSE: ${{ secrets.MEMGRAPH_ENTERPRISE_LICENSE }}
      MEMGRAPH_ORGANIZATION_NAME: ${{ secrets.MEMGRAPH_ORGANIZATION_NAME }}

    steps:
      - name: Set up repository
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. `0` indicates all history for all
          # branches and tags. (default: 1)
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Build deb image
        run: |
          cd ./scripts/
          sudo ./build_deb.sh master daily-deb

      - name: Build MAGE image
        run: |
          cd ./scripts/
          sudo ./build_mage_img.sh main daily-mage daily-deb

      - name: Build platform image
        run: |
          sudo ./build_platform_img.sh master daily-build ${{ secrets.PAT }}

