name: Release full Memgraph Platform

on:
  workflow_dispatch:
    inputs:
      memgraph_platform_version:
        description: "Memgraph Platform version."
        required: true
      memgraph_version:
        description: "Memgraph version that will be integrated into platform."
        required: true
      force_release:
        description: >
          "Force the release despite the version already exists on DockerHub."
        type: boolean
        required: false
        default: false
      docker_repository_name:
        description: "Dockerhub repository to upload to. (Mainly for testing)"
        required: false
        default: memgraph-platform

env:
  DOCKER_ORGANIZATION_NAME: memgraph
  DOCKER_REPOSITORY_NAME: ${{ github.event.inputs.docker_repository_name }}

# Reason for separating ARM and AMD is speed, buildx is extremely slow when
# building for ARM on AMD, and it is better to use native ARM machine to build
# that image
jobs:
  release-memgraph-platform-amd:
    runs-on: [self-hosted, Linux, X64, Diff]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Get Memgraph Lab release version
        run: |
          cd lab
          git fetch --all --tags
          MEMGRAPH_LAB_VERSION=$(git rev-parse --verify HEAD | git tag --contains)
          echo $MEMGRAPH_LAB_VERSION
          echo "LAB_VERSION=${MEMGRAPH_LAB_VERSION:1}" >> $GITHUB_ENV

      - name: Get Memgraph Mage release version
        run: |
          cd mage
          git fetch --all --tags
          MEMGRAPH_MAGE_VERSION=$(git rev-parse --verify HEAD | git tag --contains)
          echo $MEMGRAPH_MAGE_VERSION
          MEMGRAPH_MAGE_VERSION=${MEMGRAPH_MAGE_VERSION#v}
          echo "MAGE_VERSION=${MEMGRAPH_MAGE_VERSION%%-*}" >> $GITHUB_ENV

      - name: Set Memgraph Platform version
        run: |
          echo "PLATFORM_VERSION=${{ github.event.inputs.memgraph_platform_version }}-memgraph${{ github.event.inputs.memgraph_version }}-lab${{ env.LAB_VERSION }}-mage${{ env.MAGE_VERSION }}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download memgraph binaries
        run: |
          curl -L https://deps.memgraph.io/sayari-2.14.0-1_amd64.deb > memgraph-amd64.deb

      - name: Build & push docker images
        run: |
          docker buildx build \
          --build-arg BINARY_NAME="memgraph-" \
          --build-arg NPM_PACKAGE_TOKEN="${{ secrets.PAT }}" \
          --platform linux/amd64 \
          --tag $DOCKER_ORGANIZATION_NAME/$DOCKER_REPOSITORY_NAME:${{ env.PLATFORM_VERSION }}-amd \
          .
          docker save $DOCKER_ORGANIZATION_NAME/$DOCKER_REPOSITORY_NAME:${{ env.PLATFORM_VERSION }}-amd | gzip > docker_image.tar.gz

      - name: "Upload docker image"
        uses: actions/upload-artifact@v4
        with:
          name: "docker_image"
          path: "docker_image.tar.gz"
